### ISSUE TITLE
Error when trying to create a h2 database

### ISSUE THREAD

**Issue by baudoliver7** [Minlessika/lightweight-db#52]
The class `EmbeddedH2DataSource` throws an error with message :
```console
Unknown mode H2
```

**Comment by zoeself** [comment]
@baudoliver7 thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@baudoliver7 I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.
