### ISSUE TITLE
Remove dependency `HikariCP`

### ISSUE THREAD

**Issue by baudoliver7** [Minlessika/lightweight-db#53]
We notice that `lightweight-db` requires `HikariCP` to work. We should remove this dependency.

**Comment by zoeself** [comment]
@baudoliver7 thank you for reporting this. I'll assign someone to take care of it soon.

**Comment by zoeself** [comment]
@baudoliver7 I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.
