### ISSUE TITLE
Release version `0.4.1`

### ISSUE THREAD

**Issue by baudoliver7** [Minlessika/lightweight-db#57]
We add liquibase generation to a transaction.

**Comment by zoeself** [comment]
@baudoliver7 thank you for reporting this. Unfortunately, @baudoliver7 is not a contributor with the required role (DEV), that's why I unassigned them. 

I will assign a contributor to take care of it soon.

**Comment by baudoliver7** [comment]
@rultor release, tag is `0.4.1`

**Comment by zoeself** [comment]
@baudoliver7 I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.
