### ISSUE TITLE
Use some useful librairies

### ISSUE THREAD

**Issue by baudoliver7** [Minlessika/lightweight-db#59]
Use `jdbc-toolset` and `easy-liquibase4j`.

**Comment by zoeself** [comment]
@baudoliver7 thank you for reporting this. Unfortunately, @baudoliver7 is not a contributor with the required role (DEV), that's why I unassigned them. 

I will assign a contributor to take care of it soon.

**Comment by baudoliver7** [comment]
@zoeself help

**Comment by zoeself** [comment]
> @zoeself help

@baudoliver7 didn't understand that, sorry.

**Comment by baudoliver7** [comment]
@zoeself status

**Comment by zoeself** [comment]
> @zoeself status

@baudoliver7 this ticket is registered as a task, I will assign it to someone soon.Needed role here is ``DEV`` and estimation is ``60`` minutes.

**Comment by zoeself** [comment]
@baudoliver7 I couldn't find any assignee for this task. This is either because there are no contributors with role ``DEV`` available or because the project does not have enough funds.

Please, make sure there is at least one available contributor with the required role and the project can afford to pay them.
